### ISSUE TITLE
Is there an example of how to create a multiple select dropdown?

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [NejcZdovc/ng2-select2#32]
Hi,

Trying to find my way around this library. Is there an example of how to create a multiple select dropdown?

Thanks
Tam

**Comment by NejcZdovc** [comment]
Currently it's not supported. @krusematt created PR for enabling it, but I will try to add almost all options today with a new logic. On one hand adding every single option via input is easy, but if you need to modify a lot of options, you would have a lot of inputs. Also from implementation view stand point that would mean that I would need to add a lot of inputs into the wrapper. This is why the new logic will have only one input `options` where you would pass all options of select2 that you want and that's it.

Hope that I will manage to implement this logic today and this will also mean a new major version, because it will be a breaking change.

**Comment by NejcZdovc** [comment]
I just released version 1.0.0-beta.0 which enable you to have multiple options. Please try it out and let me know if it's working correctly.
