### ISSUE TITLE
Server side pagination

### ISSUE THREAD

**Issue by fayilt** [NejcZdovc/ng2-select2#40]
Hi,

Select2 supports server side pagination, have you implemented that as well?

Thanks

**Comment by NejcZdovc** [comment]
I am not sure what do you mean by that. Are you talking about ajax option https://select2.github.io/examples.html#data-ajax?

**Comment by fayilt** [comment]
Yes, sorry, that's exactly what I mean. Is that implemented in ng2-select2?

**Comment by NejcZdovc** [comment]
I didn't test it, but in theory you should pass ajax property into a object which you then pass into `[data]` attribute. This is completely select2 implementation.

I don't know your scenario, but I would suggest to get data via http request (Angular style) rather then ajax option of select2 and then use observables and async pipe for `[data]` attribute.

You can find example here: [Live](https://nejczdovc.github.io/ng2-select2/) and [Code](https://github.com/NejcZdovc/ng2-select2/tree/demo/src/app/demos/dynamic)

**Comment by NejcZdovc** [comment]
If you have any more questions please let me know

**Comment by pajaroblanco** [comment]
I want to avoid using the select2 ajax option and use an angular service instead. I need to be able to pass the search term to the angular service in order to perform the search on the server and then pass the results back. In your example it's just returning static data via an observable. I need to be able to return dynamic data via an observable based on what the user has searched for in the select2 input. Is there any way to get the search term from the select2 input as the user types?
